[ERROR] 2018-01-31 21:40:47,299 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:40:47.290568-127.0.0.1-36a
[ERROR] 2018-01-31 21:45:05,818 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:05.779855-127.0.0.1-3fb
[ERROR] 2018-01-31 21:45:06,106 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:06.099567-127.0.0.1-89b
[ERROR] 2018-01-31 21:45:46,113 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:46.061733-127.0.0.1-9cb
[ERROR] 2018-01-31 21:45:47,316 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:47.283597-127.0.0.1-e9a
[ERROR] 2018-01-31 21:45:47,601 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:47.593657-127.0.0.1-1c2
[ERROR] 2018-01-31 21:45:55,671 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:55.663839-127.0.0.1-a9c
[ERROR] 2018-01-31 21:45:56,682 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-31 21:45:56.674729-127.0.0.1-179
